// FontAwesome Configuration
import { library } from '@fortawesome/fontawesome-svg-core';
import { config } from '@fortawesome/fontawesome-svg-core';

// Import all the icons we'll use throughout the application
import {
  // Dashboard & Analytics
  faChartLine,
  faChartBar,
  faChartPie,
  faChartArea,
  faTachometerAlt,
  faAnalytics,
  
  // Users & People
  faUsers,
  faUser,
  faUserGraduate,
  faUserTie,
  faUserCheck,
  faUserCog,
  faUserShield,
  
  // Education & Academic
  faGraduationCap,
  faBook,
  faBookOpen,
  faUniversity,
  faSchool,
  faChalkboardTeacher,
  faUserGraduate as faStudent,
  faCertificate,
  faAward,
  faMedal,
  
  // Financial & Money
  faDollarSign,
  faMoneyBillWave,
  faCoins,
  faCreditCard,
  faReceipt,
  faCalculator,
  faHandHoldingUsd,
  faMoneyCheckAlt,
  faPiggyBank,
  faChartLineUp,
  
  // Business & Operations
  faBuilding,
  faIndustry,
  faBriefcase,
  faHandshake,
  faClipboardList,
  faFileInvoice,
  faFileContract,
  faFolderOpen,
  faArchive,
  
  // Technology & System
  faDesktop,
  faLaptop,
  faMobile,
  faServer,
  faDatabase,
  faCloud,
  faWifi,
  faCode,
  faCog,
  faCogs,
  
  // Navigation & UI
  faHome,
  faBars,
  faTimes,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faChevronRight,
  faChevronLeft,
  faChevronUp,
  faChevronDown,
  faAngleRight,
  faAngleLeft,
  faAngleUp,
  faAngleDown,
  
  // Actions & Controls
  faPlay,
  faPause,
  faStop,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faDownload,
  faUpload,
  faPrint,
  faShare,
  faCopy,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  
  // Status & Indicators
  faCheck,
  faCheckCircle,
  faTimes as faX,
  faTimesCircle,
  faExclamation,
  faExclamationTriangle,
  faExclamationCircle,
  faInfo,
  faInfoCircle,
  faQuestion,
  faQuestionCircle,
  faBell,
  faBellSlash,
  
  // Communication
  faEnvelope,
  faPhone,
  faComments,
  faComment,
  faMessage,
  
  // Security & Access
  faLock,
  faUnlock,
  faKey,
  faShield,
  faShieldAlt,
  faUserShield as faSecurityUser,
  faEye,
  faEyeSlash,
  
  // Inventory & Assets
  faBoxes,
  faBox,
  faWarehouse,
  faTruck,
  faShoppingCart,
  faShoppingBag,
  faPackage,
  faInventory,
  
  // Time & Calendar
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarPlus,
  faClock,
  faStopwatch,
  faHourglass,
  
  // Documents & Files
  faFile,
  faFileAlt,
  faFilePdf,
  faFileExcel,
  faFileWord,
  faFileImage,
  faFolder,
  faFolderOpen as faFolderOpened,
  
  // Settings & Configuration
  faSliders,
  faWrench,
  faScrewdriver,
  faTools,
  faAdjust,
  
  // Geography & Location
  faMapMarker,
  faMapMarkerAlt,
  faGlobe,
  faGlobeAfrica,
  faFlag,
  
  // Miscellaneous
  faStar,
  faHeart,
  faThumbsUp,
  faThumbsDown,
  faLightbulb,
  faRocket,
  faGem,
  faCrown,
  faFire,
  faZap,
  faBolt,
  faMagic,
  
  // Trends & Growth
  faTrendingUp,
  faTrendingDown,
  faLevelUp,
  faLevelDown,
  faGrowth,
  
  // Social & External
  faLink,
  faExternalLink,
  faShareAlt,
  
} from '@fortawesome/free-solid-svg-icons';

import {
  // Regular icons (outline versions)
  faUser as faUserRegular,
  faEnvelope as faEnvelopeRegular,
  faCalendar as faCalendarRegular,
  faFile as faFileRegular,
  faFolder as faFolderRegular,
  faHeart as faHeartRegular,
  faStar as faStarRegular,
  faCheckCircle as faCheckCircleRegular,
  faTimesCircle as faTimesCircleRegular,
  faQuestionCircle as faQuestionCircleRegular,
  faInfoCircle as faInfoCircleRegular,
  faExclamationCircle as faExclamationCircleRegular,
} from '@fortawesome/free-regular-svg-icons';

import {
  // Brand icons
  faGithub,
  faTwitter,
  faFacebook,
  faLinkedin,
  faInstagram,
  faYoutube,
  faGoogle,
  faMicrosoft,
  faApple,
  faReact,
  faNodeJs,
  faJs,
  faHtml5,
  faCss3,
  faBootstrap,
  faFigma,
  faSlack,
} from '@fortawesome/free-brands-svg-icons';

// Prevent FontAwesome from adding its CSS since we'll add it manually
config.autoAddCss = false;

// Add all icons to the library
library.add(
  // Solid icons
  faChartLine,
  faChartBar,
  faChartPie,
  faChartArea,
  faTachometerAlt,
  faUsers,
  faUser,
  faUserGraduate,
  faUserTie,
  faUserCheck,
  faUserCog,
  faUserShield,
  faGraduationCap,
  faBook,
  faBookOpen,
  faUniversity,
  faSchool,
  faChalkboardTeacher,
  faStudent,
  faCertificate,
  faAward,
  faMedal,
  faDollarSign,
  faMoneyBillWave,
  faCoins,
  faCreditCard,
  faReceipt,
  faCalculator,
  faHandHoldingUsd,
  faMoneyCheckAlt,
  faPiggyBank,
  faBuilding,
  faIndustry,
  faBriefcase,
  faHandshake,
  faClipboardList,
  faFileInvoice,
  faFileContract,
  faFolderOpen,
  faArchive,
  faDesktop,
  faLaptop,
  faMobile,
  faServer,
  faDatabase,
  faCloud,
  faWifi,
  faCode,
  faCog,
  faCogs,
  faHome,
  faBars,
  faTimes,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faChevronRight,
  faChevronLeft,
  faChevronUp,
  faChevronDown,
  faAngleRight,
  faAngleLeft,
  faAngleUp,
  faAngleDown,
  faPlay,
  faPause,
  faStop,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faDownload,
  faUpload,
  faPrint,
  faShare,
  faCopy,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faCheck,
  faCheckCircle,
  faX,
  faTimesCircle,
  faExclamation,
  faExclamationTriangle,
  faExclamationCircle,
  faInfo,
  faInfoCircle,
  faQuestion,
  faQuestionCircle,
  faBell,
  faBellSlash,
  faEnvelope,
  faPhone,
  faComments,
  faComment,
  faMessage,
  faLock,
  faUnlock,
  faKey,
  faShield,
  faShieldAlt,
  faSecurityUser,
  faEye,
  faEyeSlash,
  faBoxes,
  faBox,
  faWarehouse,
  faTruck,
  faShoppingCart,
  faShoppingBag,
  faPackage,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarPlus,
  faClock,
  faStopwatch,
  faHourglass,
  faFile,
  faFileAlt,
  faFilePdf,
  faFileExcel,
  faFileWord,
  faFileImage,
  faFolder,
  faFolderOpened,
  faSliders,
  faWrench,
  faScrewdriver,
  faTools,
  faAdjust,
  faMapMarker,
  faMapMarkerAlt,
  faGlobe,
  faGlobeAfrica,
  faFlag,
  faStar,
  faHeart,
  faThumbsUp,
  faThumbsDown,
  faLightbulb,
  faRocket,
  faGem,
  faCrown,
  faFire,
  faZap,
  faBolt,
  faMagic,
  faTrendingUp,
  faTrendingDown,
  faLevelUp,
  faLevelDown,
  faLink,
  faExternalLink,
  faShareAlt,

  // Regular icons
  faUserRegular,
  faEnvelopeRegular,
  faCalendarRegular,
  faFileRegular,
  faFolderRegular,
  faHeartRegular,
  faStarRegular,
  faCheckCircleRegular,
  faTimesCircleRegular,
  faQuestionCircleRegular,
  faInfoCircleRegular,
  faExclamationCircleRegular,

  // Brand icons
  faGithub,
  faTwitter,
  faFacebook,
  faLinkedin,
  faInstagram,
  faYoutube,
  faGoogle,
  faMicrosoft,
  faApple,
  faReact,
  faNodeJs,
  faJs,
  faHtml5,
  faCss3,
  faBootstrap,
  faFigma,
  faSlack,
);

export { library };
